{{- if and .Values.metricsEnabled .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "netbox.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "netbox.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    {{- with .Values.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.scrapeTimeout  }}
    scrapeTimeout: {{ . }}
    {{- end }}
{{- end }}
